version: "3.9"

services:

    app:
        container_name: efiempresa
        image: juandiegozb/efiempresa:1.0.1
        build: .
        volumes:
            - .:/var/www/html
        ports:
            - "8000:8000"
        env_file:
            -   .env
        depends_on:
            - db

    db:
        container_name: db
        image: postgres:12
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER : efiempresa
            POSTGRES_PASSWORD : J2a2f56b0@
            POSTGRES_DB: efiempresa_db
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: {}
